/* ------------------------------ Essentials ------------------------------ */
const ESSENTIALS_ICON_COLOR = {
  PRIMARY: '#865AD2',
};

/* ------------------------------ States ------------------------------ */
const COMPASS_ICON_COLOR = {
  FOCUS_COMPASS: '#301E53',
  HOVER_COMPASS: '#301E53',
  ACTIVE_COMPASS: '#F9F9F9',
  DISABLED_COMPASS: '#865AD2',
  DEFAULT_COMPASS: '#301E53',
};

const RECTANGLE_ICON_COLOR = {
  FOCUS_RECTANGLE: '#BCB2F8',
  HOVER_RECTANGLE: '#F1EBC8',
  ACTIVE_RECTANGLE: '#865AD2',
  DISABLED_RECTANGLE: '#000',
  DEFAULT_RECTANGLE: '#000',
};

const MAPPING_STATE_ICON_COLOR = {
  FOCUS: {
    COMPASS_ICON_COLOR: COMPASS_ICON_COLOR.FOCUS_COMPASS,
    RECTANGLE_ICON_COLOR: RECTANGLE_ICON_COLOR.FOCUS_RECTANGLE,
  },
  HOVER: {
    COMPASS_ICON_COLOR: COMPASS_ICON_COLOR.HOVER_COMPASS,
    RECTANGLE_ICON_COLOR: RECTANGLE_ICON_COLOR.HOVER_RECTANGLE,
  },
  ACTIVE: {
    COMPASS_ICON_COLOR: COMPASS_ICON_COLOR.ACTIVE_COMPASS,
    RECTANGLE_ICON_COLOR: RECTANGLE_ICON_COLOR.ACTIVE_RECTANGLE,
  },
  DISABLED: {
    COMPASS_ICON_COLOR: COMPASS_ICON_COLOR.DISABLED_COMPASS,
    RECTANGLE_ICON_COLOR: RECTANGLE_ICON_COLOR.DISABLED_RECTANGLE,
  },
  DEFAULT: {
    COMPASS_ICON_COLOR: COMPASS_ICON_COLOR.DEFAULT_COMPASS,
    RECTANGLE_ICON_COLOR: RECTANGLE_ICON_COLOR.DEFAULT_RECTANGLE,
  },
};

/* ------------------------------ Statuses ------------------------------ */
const STATUS_ICON_COLOR = {
  ERROR: '#DD7249',
  WARNING: '#DBD07A',
  SUCCESS: '#649C5A',
  INFO: '#865AD2',
  DEFAULT: '#000000',
};

/* ------------------------------ loaders ------------------------------ */
const LOADER_ICON_COLOR = {
  PRIMARY: '#865AD2',
};

export {
  ESSENTIALS_ICON_COLOR,
  COMPASS_ICON_COLOR,
  RECTANGLE_ICON_COLOR,
  MAPPING_STATE_ICON_COLOR,
  STATUS_ICON_COLOR,
  LOADER_ICON_COLOR,
};
